#!/usr/bin/env bash

CHROOT_TOR_SCHEMA_VERSION=1
CHROOT_TOR_DEFAULT_SOCKS_PORT=49050
CHROOT_TOR_DEFAULT_TRANS_PORT=49040
CHROOT_TOR_DEFAULT_DNS_PORT=49053
CHROOT_TOR_DEFAULT_CONTROL_PORT=49051
CHROOT_TOR_BOOTSTRAP_TIMEOUT_SEC_DEFAULT=45
CHROOT_TOR_CHAIN_NAT="AURORA_TOR_NAT"
CHROOT_TOR_CHAIN_FILTER="AURORA_TOR_FILT"
CHROOT_TOR_CHAIN_FILTER6="AURORA_TOR6_FILT"
CHROOT_TOR_POLICY_V4_TABLE=52040
CHROOT_TOR_POLICY_V6_TABLE=52041
CHROOT_TOR_POLICY_V4_PREF_BASE=28000
CHROOT_TOR_POLICY_V4_PREF_END=29999
CHROOT_TOR_POLICY_V6_PREF_BASE=30000
CHROOT_TOR_POLICY_V6_PREF_END=30999
CHROOT_TOR_LAST_RULE_ERROR="${CHROOT_TOR_LAST_RULE_ERROR:-}"

if ! declare -p CHROOT_TOR_POLICY_V4_ACTIVE_PREFS >/dev/null 2>&1; then
  declare -ag CHROOT_TOR_POLICY_V4_ACTIVE_PREFS=()
fi
if ! declare -p CHROOT_TOR_POLICY_V6_ACTIVE_PREFS >/dev/null 2>&1; then
  declare -ag CHROOT_TOR_POLICY_V6_ACTIVE_PREFS=()
fi

CHROOT_TOR_BIN="${CHROOT_TOR_BIN:-}"
CHROOT_TOR_IPTABLES_BIN="${CHROOT_TOR_IPTABLES_BIN:-}"
CHROOT_TOR_IP6TABLES_BIN="${CHROOT_TOR_IP6TABLES_BIN:-}"
CHROOT_TOR_IP_BIN="${CHROOT_TOR_IP_BIN:-}"
CHROOT_TOR_CMD_BIN="${CHROOT_TOR_CMD_BIN:-}"
CHROOT_TOR_PM_BIN="${CHROOT_TOR_PM_BIN:-}"
CHROOT_TOR_DUMPSYS_BIN="${CHROOT_TOR_DUMPSYS_BIN:-}"
CHROOT_TOR_UID_SOURCE="${CHROOT_TOR_UID_SOURCE:-}"

chroot_tor_run_mode_uses_saved_bypass() {
  case "${1:-default}" in
    configured|configured-apps) return 0 ;;
    *) return 1 ;;
  esac
}

chroot_tor_run_mode_uses_saved_exit() {
  case "${1:-default}" in
    configured|configured-exit) return 0 ;;
    *) return 1 ;;
  esac
}
