chroot_set_runtime_root() {
  local root="$1"
  CHROOT_RUNTIME_ROOT="$root"
  CHROOT_MANIFEST_DIR="$CHROOT_RUNTIME_ROOT/manifests"
  CHROOT_CACHE_DIR="$CHROOT_RUNTIME_ROOT/cache"
  CHROOT_ROOTFS_DIR="$CHROOT_RUNTIME_ROOT/rootfs"
  CHROOT_STATE_DIR="$CHROOT_RUNTIME_ROOT/state"
  CHROOT_BACKUPS_DIR="$CHROOT_RUNTIME_ROOT/backups"
  CHROOT_LOG_DIR="$CHROOT_RUNTIME_ROOT/logs"
  CHROOT_LOCK_DIR="$CHROOT_RUNTIME_ROOT/locks"
  CHROOT_TMP_DIR="$CHROOT_RUNTIME_ROOT/tmp"
  CHROOT_SETTINGS_FILE="$CHROOT_STATE_DIR/settings.json"
  CHROOT_MANIFEST_FILE="$CHROOT_MANIFEST_DIR/index.json"
  CHROOT_MANIFEST_META_FILE="$CHROOT_MANIFEST_DIR/index.meta.json"
}

