chroot_runtime_layout_dirs() {
  cat <<DIRS
$CHROOT_RUNTIME_ROOT
$CHROOT_MANIFEST_DIR
$CHROOT_CACHE_DIR
$CHROOT_ROOTFS_DIR
$CHROOT_STATE_DIR
$CHROOT_BACKUPS_DIR
$CHROOT_LOG_DIR
$CHROOT_LOCK_DIR
$CHROOT_TMP_DIR
DIRS
}

